"""add is_approved to users

Revision ID: 80de3e1683f1
Revises: 5821fd117863
Create Date: 2026-04-01 14:57:44.725976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80de3e1683f1'
down_revision: Union[str, None] = '5821fd117863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_approved', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_approved')
    # ### end Alembic commands ###
