"""initial tables

Revision ID: cf4062e225da
Revises: 
Create Date: 2026-03-28 15:55:41.614292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf4062e225da'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('analyst_id', sa.String(), nullable=True),
    sa.Column('category', sa.Enum('INDEX', 'STOCK', 'COMMODITY', name='alertcategory'), nullable=False),
    sa.Column('direction', sa.Enum('BULLISH', 'BEARISH', name='alertdirection'), nullable=False),
    sa.Column('exchange', sa.String(), nullable=False),
    sa.Column('contract', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('ltp', sa.Float(), nullable=False),
    sa.Column('strike', sa.Float(), nullable=False),
    sa.Column('option_ltp', sa.Float(), nullable=False),
    sa.Column('lot_size', sa.Integer(), nullable=False),
    sa.Column('investment', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'DRAFT', name='alertstatus'), server_default='DRAFT', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analyst_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_analyst_id'), 'alerts', ['analyst_id'], unique=False)
    op.create_table('analysts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('avatar_bg', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('analyst_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('action', sa.Enum('BUY', 'SELL', 'HOLD', name='recoaction'), nullable=False),
    sa.Column('sector', sa.String(), nullable=False),
    sa.Column('cmp', sa.Float(), nullable=False),
    sa.Column('target', sa.Float(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', name='recostatus'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analyst_id'], ['analysts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_analyst_id'), 'recommendations', ['analyst_id'], unique=False)
    op.drop_table('customers')
    op.add_column('refresh_tokens', sa.Column('token', sa.String(), nullable=False))
    op.add_column('refresh_tokens', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('refresh_tokens', 'refresh_token')
    op.drop_column('refresh_tokens', 'updated_at')
    op.add_column('users', sa.Column('password', sa.String(), nullable=False))
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('USER', 'ADMIN', 'Analyst', name='role'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'role',
               existing_type=sa.String(),
               type_=postgresql.ENUM('USER', 'ADMIN', 'Analyst', name='role'),
               existing_nullable=False)
    op.drop_column('users', 'password')
    op.add_column('refresh_tokens', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('refresh_tokens', sa.Column('refresh_token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_column('refresh_tokens', 'created_at')
    op.drop_column('refresh_tokens', 'token')
    op.create_table('customers',
    sa.Column('customerid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('firstname', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('lastname', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('customerid', name='customers_pkey')
    )
    op.drop_index(op.f('ix_recommendations_analyst_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_table('analysts')
    op.drop_index(op.f('ix_alerts_analyst_id'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
